print("please enter the following information:")
print()

first_name =input("first name:")
last_name = input("Last_name: ")
email_address = input("Email address: ") 
phone_number = input("Phone_number: ")
job_title = input("Job title: ")
id_number = input("ID number:")

print("\nThe ID Card is:")
print("---------------------------")
print(f"{last_name},{first_name}")
print(f"job_title")
print(f"ID: {id}")
print()
print(f"{email_address}")
print(f"{phone_number}")
print("---------------------------")
